#%RAML 1.0 Library

types:
  Song:
    description: |
      A song.
    properties:
      title: string
      length: number
    examples:
      song1:
        strict: false
        value:
          title: "My Song"
          length: 12
      song2:
        title: "Last"
        length: 3
  Songs:
    type: Song[]
    minItems: 1
    maxItems: 20
    uniqueItems: true
  Album:
    properties:
      title: string
      songs: Songs
  Albums:
    type: Album[]
  Musician:
    description: |
      The artist of a song.
    properties:
      name: string
      discography: (Song | Album)[]
